Controllers/DataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;
using WebApplication1.Models.BLL;
using WebApplication1.Models.DAL;

namespace WebApplication1.Controllers
{
    public class DataController : Controller
    {
        // GET: Data
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult UploadFile()
        {
            return View();
        }

        [HttpPost]
        public ActionResult UploadFile(HttpPostedFileBase file)
        {
            var fileName = file.FileName;
            var filePath = Server.MapPath(string.Format("~/{0}", "File"));
            file.SaveAs(Path.Combine(filePath, fileName));
            return View();
        }


        public ActionResult Address()
        {

            return View();
        }

        List<SelectListItem> items = new List<SelectListItem>();
        List<string> date = new List<string>();
        public static List<全国行政区划代码表> plist = new List<全国行政区划代码表>();
        private ProvinceServices pss = new ProvinceServices();

        #region 加载省
        /// <summary>
        /// 加载省
        /// </summary>
        /// <returns></returns>
        public JsonResult Provinces()
        {

            var list = pss.GetProvinces();
            foreach (var item in list)
            {
                date.Add(item.地区名称);

                items.Add(new SelectListItem()
                {
                    Text = string.Concat("", " ", item.地区名称),
                    Value = item.地区编码.ToString()
                });
            }
            if (!items.Count.Equals(0))
            {
                items.Insert(0, new SelectListItem() { Text = "选择省", Value = "" });
            }

            return Json(items, JsonRequestBehavior.AllowGet);

        }

        #endregion

        #region 加载市
        /// <summary>
        /// 加载市
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult GetCities(string id)
        {
            var list = pss.city(id);
            foreach (var item in list)
            {
                date.Add(item.地区名称);

                items.Add(new SelectListItem()
                {
                    Text = string.Concat("", " ", item.地区名称),
                    Value = item.地区编码.ToString()
                });
            }
            if (!items.Count.Equals(0))
            {
                items.Insert(0, new SelectListItem() { Text = "选择市", Value = "" });
            }
            return Json(items, JsonRequestBehavior.AllowGet);

        }

        #endregion

        #region 加载区

        /// <summary>
        /// 加载区
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public JsonResult Area(string id)
        {
            var list = pss.city(id);
            foreach (var item in list)
            {
                date.Add(item.地区名称);

                items.Add(new SelectListItem()
                {
                    Text = string.Concat("", " ", item.地区名称),
                    Value = item.地区编码.ToString()
                });
            }
            //if (!items.Count.Equals(0))
            //{
            //    items.Insert(0, new SelectListItem() { Text = "请选择", Value = "" });
            //}
            return Json(items, JsonRequestBehavior.AllowGet);

        }
        #endregion



        private UserManager user = new UserManager();
        Users model = new Users();

        #region 保存地址

        [HttpPost]
        public JsonResult Address1(string p, string c, string a)
        {
            model.Address = p + c + a;
            user.Register(model);
            return Json(new { status = 1, msg = "地址添加成功!" });
        }
        #endregion

    }
}

Views/Data/Address.cshtml
<div class="layui-body">
    <form method="post" action="/Data/Address" id="myform">

        <select id="p" name="p">
            <option value="-1" selected=selected>--选择省--</option>
        </select>
        <select id="c" name="c">
            <option value="-1" selected=selected>--选择市--</option>
        </select>
        <select id="a">
            <option value="-1" selected=selected>--选择区--</option>
        </select><br /><br /><br />
        <input type="button" onclick="submitform()" value="保存地址" />
    </form>
</div>

@section scripts
  {
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script type="text/javascript">

        $(function () {
            getProvince();
            $('#p').change(function () {
                changeCity();
                Area();
            });
            $('#c').change(function () {
                Area();
            });
        });

 //加载省
        function getProvince() {
$.getJSON('@Url.Action("Provinces", "Data")', function (data) {
    $('#p').empty();
    $.each(data, function (i, item)
    {
        $('#p').append($('<option></option>').val(item.Value).text(item.Text));
    });
            });
        }

 //设置城市清空
        function emptyCity() {
            $('#c').empty();
            $('#c').append($('<option></option>').val('').text('请选择'));
        }

 //根据省加载城市

        function changeCity() {
            var selectedProvinceId = $.trim($('#p option:selected').val());
            if (selectedProvinceId.length == 0) {
                emptyCity();
            } else {
            $.getJSON('@Url.Action("GetCities", "Data")', { id: selectedProvinceId }, function (data) {
                $('#c').empty();
            $.each(data, function (i, item) {
                $('#c').append($('<option></option>').val(item.Value).text(item.Text));
                });
                });
            }
        }

        //设置清空区
        function emptyArea() {
            $('#a').empty();
            $('#a').append($('<option></option>').val('').text('请选择'));
        }
        //根据市加载区
        function Area() {
            //alert(111);
            var selectedCityId = $.trim($('#c option:selected').val());
            // alert(222);
            if (selectedCityId.length == 0) {
                emptyArea();
            } else {
 $.getJSON('@Url.Action("Area", "Data")', { id: selectedCityId }, function (data) {

     $('#a').empty();
     //alert(222);
     $('#a').append($(' <option value="-1" selected=selected>--选择区--</option>'));
     $.each(data, function (i, item) {
         //alert(333);
         $('#a').append($('<option></option>').val(item.Value).text(item.Text));
     });
                });
            }
        }

        function submitform() {

            var json = $("#myform").serialize();
            var p = $('#p option:selected').text();
            var c = $('#c option:selected').text();
            var a = $('#a option:selected').text();
            //alert(p);
            if (p == "-1") {
                alert("请选择省！");
                $("#p option:selected").focus();
                return false;
            }
            if (c == "-1") {
                alert("请选择市！");
                $("#c").focus();
                return false;
            }
            if (a== "-1") {
                alert("请选择区！");
                $("#a").focus();
                return false;
            }
            $.post("/Data/address1", {p:p,c:c,a:a}, function (obj) {
                alert(obj.msg)

            }, "json");

        }
    </script>
}

Views/Data/Index.cshtml
<!Doctype html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>老鼠猪统计图，订单按月统计</title>
    <link rel="stylesheet" href="" type="text/css" />
    <link rel="stylesheet" href="" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/echarts.common.min.js"></script>
</head>
<body>

    <div id="main" style="width: 1000px;height:400px;"></div>

    <script type="text/javascript">
        // 基于准备好的dom，初始化echarts实例
        var myChart = echarts.init(document.getElementById('main'));

        // 指定图表的配置项和数据
        var url="/Home/About";
        $.get(url, function (e) {
        var option = {
            title: {
                text: '订单销量统计表'
            },
            tooltip: {},
            legend: {
                data: ['日期']
            },
            xAxis: {
                data: e.日期
            },
            yAxis: {},
            series: [{
                name: '销量',
                type: 'bar',
                data: e.统计
            }]
        };

        // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
        })
    </script>
</body>
</html>

Views/Data/UploadFile.cshtml
<div class="layui-body">
    <form action="/Data/UploadFile" method="post" enctype="multipart/form-data">
        <input type="file" name="file" /><br />
        <input type="submit" value="提交" />
    </form>
</div>